from __future__ import annotations

import sys
from pathlib import Path

if __name__ == "__main__" and __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "python"))

import dragongui as dg


app = dg.App(theme=dg.Theme.dark(accent="#5aa9ff", radius=8))
app.stylesheet(
    """
    Window {
        background: #0d1320;
        color: rgba(245, 248, 255, 0.94);
        padding: 18px;
        gap: 12px;
        font-size: 14px;
    }

    VLayout.scroll-root {
        height: 620px;
        overflow-y: auto;
        padding-right: 18px;
        padding-bottom: 84px;
        gap: 12px;
    }

    VLayout.scroll-root::scrollbar-track {
        width: 8px;
        padding: 8px;
        background: rgba(255, 255, 255, 0.08);
        border-radius: 999px;
    }

    VLayout.scroll-root::scrollbar-thumb {
        width: 6px;
        background: rgba(90, 169, 255, 0.72);
        border-radius: 999px;
    }

    Panel {
        background: rgba(18, 25, 39, 0.92);
        border: 1px solid rgba(255, 255, 255, 0.14);
        border-radius: 16px;
        box-shadow: 0 12px 30px rgba(0, 0, 0, 0.24);
        padding: 12px;
        gap: 8px;
    }

    Panel.case {
        width: 356px;
        min-height: 164px;
        overflow: visible;
    }

    Label.title {
        color: white;
        font-size: 20px;
        font-weight: 800;
    }

    Label.caption {
        color: rgba(245, 248, 255, 0.74);
        line-height: 1.12;
    }

    Label.case-title {
        color: rgba(245, 248, 255, 0.96);
        font-weight: 800;
    }

    Label.pass {
        color: #74ddb0;
        font-weight: 800;
    }

    Button,
    TextInput,
    Badge {
        border-radius: 10px;
    }

    Button.literal::before {
        content: "RUN ";
        width: 42px;
        padding: 4px;
        color: #74ddb0;
        font-weight: 900;
    }

    Button.literal::after {
        content: " ->";
        width: 34px;
        padding: 4px;
        color: #ffd36a;
        font-weight: 900;
    }

    Label.prefix::before {
        content: "PASS ";
        width: 42px;
        padding: 2px;
        color: #74ddb0;
        font-weight: 900;
    }

    Label.suffix::after {
        content: " READY";
        width: 70px;
        padding: 2px;
        color: #5aa9ff;
        font-weight: 900;
    }

    Badge.level-attr::after {
        content: attr(level);
        width: 66px;
        padding: 3px;
        color: #ffd36a;
        font-size: 11px;
        font-weight: 900;
        text-align: right;
    }

    Button.key-attr::after {
        content: attr(key);
        width: 112px;
        padding: 4px;
        color: #c7d2fe;
        font-size: 11px;
        font-weight: 800;
        text-align: right;
    }

    TextInput.value-attr::after {
        content: attr(value);
        width: 98px;
        padding: 4px;
        color: #74ddb0;
        font-size: 11px;
        font-weight: 800;
        text-align: right;
    }

    Panel.title-attr::after {
        content: attr(title);
        width: 132px;
        padding: 4px;
        color: rgba(255, 211, 106, 0.96);
        font-size: 11px;
        font-weight: 900;
        text-align: right;
    }

    Button.clipped::after {
        content: " GENERATED-SUFFIX-IS-CLIPPED";
        width: 92px;
        padding: 4px;
        color: #ff8ea3;
        font-size: 11px;
        font-weight: 900;
        text-align: right;
    }

    Label.long-prefix::before {
        content: "LONG-GENERATED-PREFIX ";
        width: 76px;
        padding: 2px;
        color: #ff8ea3;
        font-weight: 900;
    }
    """
)


win = dg.Window("CSS Generated Content Probe", width=820, height=660)

with dg.VLayout(class_="scroll-root"):
    dg.Label("Generated content", class_="title")
    dg.Label(
        "This probe checks text generated by ::before and ::after. Generated content should "
        "draw as prefix/suffix text, reserve inline space when width is set, and stay clipped "
        "to the widget while scrolling.",
        class_="caption",
    )

    with dg.HLayout(style={"gap": 12}):
        with dg.Panel("Literal content", class_="case"):
            dg.Label("Quoted strings", class_="case-title")
            dg.Button("Build report", class_="literal")
            dg.Label("Generated PASS prefix on this label.", class_="prefix")
            dg.Label("Generated suffix on this label.", class_="suffix")
            dg.Label("PASS: green prefix and yellow suffix are visible.", class_="pass")

        with dg.Panel("Attribute content", class_="case"):
            dg.Label("attr(name)", class_="case-title")
            dg.Badge("queue", level="warning", class_="level-attr")
            dg.Button("Export data", key="export-button", class_="key-attr")
            dg.TextInput("draft-42", placeholder="record id", class_="value-attr")
            dg.Label("PASS: generated text mirrors level, key, and value props.", class_="pass")

    with dg.HLayout(style={"gap": 12}):
        with dg.Panel("Panel title attr", class_="case title-attr"):
            dg.Label("Panel::after", class_="case-title")
            dg.Label("The panel title should appear again as generated text on the right edge.")
            dg.Badge("attr(title)", level="info")
            dg.Label("PASS: title attr text appears inside the panel bounds.", class_="pass")

        with dg.Panel("Reserved width", class_="case"):
            dg.Label("Inline reservation", class_="case-title")
            dg.Button("Text remains centered between generated sides", class_="literal")
            dg.Button("Suffix clips to a fixed width", class_="clipped")
            dg.Label("PASS: main text is not drawn over generated content.", class_="pass")

    with dg.HLayout(style={"gap": 12}):
        with dg.Panel("Clipping", class_="case"):
            dg.Label("Fixed generated width", class_="case-title")
            dg.Label("Main text should start after a clipped generated prefix.", class_="long-prefix")
            dg.Button("Long suffix stays inside this button", class_="clipped")
            dg.Label("PASS: generated text does not spill outside its widget.", class_="pass")

        with dg.Panel("Scroll stability", class_="case title-attr"):
            dg.Label("Scroll this card", class_="case-title")
            dg.Label("Generated content should not shift, shrink, or resize near viewport edges.")
            dg.Button("Stable generated sides", class_="literal")
            dg.Badge("visible", level="success", class_="level-attr")
            dg.Label("PASS: generated content stays anchored while scrolling.", class_="pass")


if __name__ == "__main__":
    print(app.run(win))
