[package]
name = "dragongui-native"
version = "1.0.4"
edition = "2021"
description = "Rust native backend for DragonGUI."
license = "MIT"
repository = "https://github.com/NKocur/DragonGui"
publish = false
exclude = [
    ".pytest_cache/**",
    ".test-cache/**",
    "dist/**",
    "pytest-cache-files-*",
    "target/**",
]

[lib]
name = "_dragongui"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py312"] }
winit = "0.30"
wgpu = "29"
glam = "0.28"
bytemuck = { version = "1", features = ["derive"] }
ab_glyph = "0.2.32"
base64 = "0.22"
flate2 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
taffy = "0.5"
thiserror = "2"
pollster = "0.4"
glyphon = "0.11.0"
rfd = "0.15.4"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png"] }
lightningcss = { version = "=1.0.0-alpha.71", default-features = false }
cssparser = "0.33"
smallvec = "1"

[target.'cfg(windows)'.dependencies]
webview2-com = "0.38.2"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
default = []
gpu = []

