from __future__ import annotations

import argparse
import math
import subprocess
import sys
import threading
import time
from pathlib import Path

if __name__ == "__main__" and __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "python"))

import dragongui as dg

try:
    import numpy as np
except ImportError as exc:  # pragma: no cover - manual demo guard
    raise SystemExit("rpi_v4l2_phase_scatter.py requires NumPy") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Live V4L2 phase scatter viewer using DragonGUI Scatter3D."
    )
    parser.add_argument("--device", default="/dev/video0")
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--image-height", type=int, default=240)
    parser.add_argument("--frames", type=int, default=4)
    parser.add_argument(
        "--packet-header-words",
        type=int,
        default=1,
        help="Number of uint16 words to skip before each image plane. The WASP camera stream uses 1.",
    )
    parser.add_argument(
        "--pixelformat",
        default="Y12 ",
        help="V4L2 pixel format FourCC. The default includes the required trailing space for 'Y12 '.",
    )
    parser.add_argument("--sample-step", type=int, default=5)
    parser.add_argument(
        "--debug-points",
        type=int,
        default=150_000,
        help="Number of points generated by the collapsible debug fake-data buttons.",
    )
    parser.add_argument("--threshold", type=float, default=1.6)
    parser.add_argument(
        "--z-scale",
        type=float,
        default=80.0,
        help="Scale applied to phase radians when using phase as Scatter3D Z depth.",
    )
    parser.add_argument(
        "--payload",
        choices=("scalar", "xyz"),
        default="xyz",
        help="Scatter payload format: scalar packs per-point RGB, xyz sends compact x/y/z only.",
    )
    parser.add_argument("--window-width", type=int, default=800)
    parser.add_argument("--window-height", type=int, default=480)
    parser.add_argument("--attitude-size", type=float, default=138.0)
    parser.add_argument("--translation-size", type=float, default=112.0)
    parser.add_argument("--translation-range-m", type=float, default=12.0)
    parser.add_argument("--translation-ring-step-m", type=float, default=2.0)
    parser.add_argument("--translation-trail-points", type=int, default=70)
    parser.add_argument(
        "--translation-fps",
        type=float,
        default=30.0,
        help="Generated translation trace update rate until real accelerometer integration is wired in.",
    )
    parser.add_argument(
        "--translation-label-fps",
        type=float,
        default=5.0,
        help="Numeric translation label update rate.",
    )
    parser.add_argument(
        "--attitude-fps",
        type=float,
        default=60.0,
        help="Generated attitude indicator update rate until a real IMU source is wired in.",
    )
    parser.add_argument(
        "--attitude-label-fps",
        type=float,
        default=5.0,
        help="Numeric attitude label update rate.",
    )
    parser.add_argument(
        "--no-attitude-stream",
        action="store_true",
        help="Disable generated attitude indicator motion.",
    )
    parser.add_argument(
        "--no-translation-stream",
        action="store_true",
        help="Disable generated translation trace motion.",
    )
    parser.add_argument(
        "--debug-autoinject",
        choices=("none", "wave", "rings", "noise", "ramp"),
        default="none",
        help="Automatically inject fake debug points after startup for benchmark runs.",
    )
    parser.add_argument(
        "--benchmark-summary",
        action="store_true",
        help="Print a compact final timing summary instead of the full run result.",
    )
    parser.add_argument(
        "--debug-reinject-count",
        type=int,
        default=0,
        help="Benchmark mode: reapply the prepared debug payload this many times after autoinject.",
    )
    parser.add_argument(
        "--debug-reinject-interval-ms",
        type=int,
        default=100,
        help="Delay between repeated debug payload reuploads in benchmark mode.",
    )
    parser.add_argument("--autostart", action="store_true")
    return parser.parse_args()


args = parse_args()
packet_rows = args.image_height + 1
stream_height = args.frames * packet_rows
frame_words = args.width * stream_height
frame_bytes = frame_words * 2
sample_step = max(1, int(args.sample_step))
debug_points = max(8, int(args.debug_points))
z_scale = float(args.z_scale)
payload_mode = str(args.payload)

x_grid, y_grid = np.meshgrid(
    np.arange(args.width, dtype=np.float32),
    np.arange(args.image_height, dtype=np.float32),
)
sample_idx = np.arange(0, x_grid.size, sample_step, dtype=np.int64)
x_center = np.float32((args.width - 1.0) * 0.5)
y_center = np.float32((args.image_height - 1.0) * 0.5)
x_sample = x_grid.reshape(-1)[sample_idx] - x_center
y_sample = y_center - y_grid.reshape(-1)[sample_idx]
debug_x_sample = np.linspace(-x_center, x_center, debug_points, dtype=np.float32)
debug_y_sample = np.linspace(y_center, -y_center, debug_points, dtype=np.float32)
TAU = float(math.tau)

stream_cmd = [
    "v4l2-ctl",
    "-d",
    args.device,
    f"--set-fmt-video=width={args.width},height={stream_height},pixelformat={args.pixelformat}",
    "--stream-mmap",
    "--stream-count=0",
    "--stream-to=-",
]

initial_frame = {
    "x": np.array(
        [-x_center, -x_center, x_center, x_center] * 2,
        dtype=np.float32,
    ),
    "y": np.array(
        [y_center, -y_center, y_center, -y_center] * 2,
        dtype=np.float32,
    ),
    "phase": np.array(
        [-np.pi, -np.pi, -np.pi, -np.pi, np.pi, np.pi, np.pi, np.pi],
        dtype=np.float32,
    ),
    "z": np.array(
        [-np.pi, -np.pi, -np.pi, -np.pi, np.pi, np.pi, np.pi, np.pi],
        dtype=np.float32,
    )
    * np.float32(z_scale),
}

app = dg.App(theme=dg.Theme.dark(accent="#3fc7ff", focus="#ffcc33"))
app.stylesheet(
    """
Window {
    background: #0c111d;
    color: rgba(245, 248, 255, 0.94);
    font-family: "Piboto";
    font-size: 14px;
}

Panel,
Label,
Button {
    font-family: "Piboto";
    font-weight: 400;
}

Button.compact-control {
    height: 24px;
    font-size: 12px;
    padding: 2px 6px;
    border-radius: 0px;
}

Button.tiny-control {
    height: 24px;
    font-size: 12px;
    padding: 2px 5px;
    border-radius: 0px;
}

Label.compact-label {
    font-size: 12px;
    line-height: 15px;
}

Label.metric-label {
    font-size: 11px;
    line-height: 14px;
}

Label.section-label {
    color: rgba(164, 177, 202, 0.94);
    font-size: 11px;
    line-height: 13px;
}

Separator {
    margin-top: 2px;
    margin-bottom: 2px;
}

Scatter3D {
    width: 100%;
    min-height: 0;
    flex-grow: 1;
    flex-shrink: 1;
    background: rgba(4, 8, 18, 0.72);
    border-radius: 12px;
    scatter-point-style: circle;
}

Scatter3D.main-scatter {
    min-height: 0;
    flex-grow: 1;
    flex-shrink: 1;
    align-self: stretch;
}

AttitudeSphere.lidar-attitude {
    width: 100%;
    height: 138px;
}

TranslationTrace.lidar-translation {
    width: 100%;
    background: rgba(3, 8, 16, 0.78);
    border-radius: 0px;
}
"""
)
win = dg.Window("WASP LiDAR Dashboard", width=args.window_width, height=args.window_height)

LEFT_PANEL_WIDTH = 126
RIGHT_PANEL_WIDTH = 184
CONTROL_BUTTON_STYLE = {"height": 24, "width": 106, "font_size": 12, "border_radius": 0}
SMALL_BUTTON_STYLE = {"height": 24, "width": 50, "font_size": 12, "border_radius": 0}
CONTROL_LABEL_STYLE = {"font_size": 12, "line_height": "15px", "height": 17}
SECTION_LABEL_STYLE = {"font_size": 11, "line_height": "13px", "height": 15, "flex_shrink": 0}
CONTROL_SLIDER_STYLE = {"height": 24, "width": 106, "flex_shrink": 0}
RIGHT_LABEL_STYLE = {"font_size": 11, "line_height": "14px", "height": 18, "flex_shrink": 0}
ATTITUDE_WIDGET_HEIGHT = int(float(args.attitude_size)) + 22
ATTITUDE_PANEL_HEIGHT = max(214, ATTITUDE_WIDGET_HEIGHT + 48)
TRANSLATION_PANEL_HEIGHT = max(156, int(float(args.translation_size)) + 44)
TRANSLATION_LABEL_STYLE = {
    "font_size": 11,
    "line_height": "14px",
    "height": 18,
    "width": 80,
    "flex_shrink": 0,
}

stop_event = threading.Event()
stream_thread: threading.Thread | None = None
stream_proc: subprocess.Popen[bytes] | None = None
state = {
    "frames": 0,
    "last_pack_ms": 0.0,
    "last_points": 0,
    "last_error": "",
    "threshold": float(args.threshold),
    "pitch": 0.0,
    "roll": 0.0,
    "yaw": 0.0,
    "translation_x": 0.0,
    "translation_y": 0.0,
}
debug_rng = np.random.default_rng(2877)
debug_payloads: dict[str, dg.ScatterPayload] = {}
debug_payloads_lock = threading.Lock()
attitude_stop_event = threading.Event()
attitude_thread: threading.Thread | None = None
translation_stop_event = threading.Event()
translation_thread: threading.Thread | None = None


def prepare_scatter_payload(
    frame: dict[str, np.ndarray],
    *,
    point_size: float,
) -> dg.ScatterPayload:
    if payload_mode == "xyz":
        return dg.Scatter3D.prepare_points(
            frame,
            x="x",
            y="y",
            z="z",
            colormap="turbo",
        )
    return dg.Scatter3D.prepare_points(
        frame,
        x="x",
        y="y",
        z="z",
        scalars="phase",
        colormap="turbo",
        point_size=point_size,
        nan_color=(0.03, 0.03, 0.03),
    )


def set_status(text: str) -> None:
    status.set_value(text)


def make_phase_payload(raw: np.ndarray) -> dg.ScatterPayload:
    planes = []
    header_words = max(0, int(args.packet_header_words))
    for frame_index in range(args.frames):
        start = frame_index * args.width * packet_rows + header_words
        end = start + args.width * args.image_height
        planes.append(raw[start:end].reshape(args.image_height, args.width))

    data = np.stack(planes, axis=2).astype(np.float32, copy=False)
    centered = data - np.mean(data, axis=2, keepdims=True)
    q = data[:, :, 3] - data[:, :, 1]
    i = data[:, :, 0] - data[:, :, 2]
    phase = np.arctan2(q, i).astype(np.float32, copy=False)
    intensity = np.log10(np.sum(np.abs(centered) + 1.0, axis=2))

    phase_flat = phase.reshape(-1).copy()
    threshold = float(state["threshold"])
    phase_flat[intensity.reshape(-1) <= threshold] = np.nan
    phase_sample = phase_flat[sample_idx].astype(np.float32, copy=False)

    frame = {
        "x": x_sample,
        "y": y_sample,
        "z": phase_sample * np.float32(z_scale),
        "phase": phase_sample,
    }
    return prepare_scatter_payload(frame, point_size=1.5)


def update_metrics() -> None:
    status.set_value(
        f"frames={state['frames']} points={state['last_points']} "
        f"pack={state['last_pack_ms']:.2f}ms"
    )
    points_value.set_value(f"Pts {state['last_points']:,}")
    pack_value.set_value(f"Pack {state['last_pack_ms']:.1f} ms")
    frames_value.set_value(f"Frames {state['frames']}")


def set_translation_labels(x: float, y: float) -> None:
    translation_x_value.set_value(f"X {x:0.2f} m")
    translation_y_value.set_value(f"Y {y:0.2f} m")


def set_threshold(value: float) -> None:
    threshold = float(value)
    state["threshold"] = threshold
    threshold_value.set_value(f"Threshold {threshold:0.2f}")


def generated_attitude(t: float) -> tuple[float, float, float]:
    pitch = math.sin(t * 0.72) * 28.0
    roll = math.sin(t * 0.48 + 0.7) * 42.0
    yaw = (t * 28.0) % 360.0
    return pitch, roll, yaw


def generated_translation(t: float) -> tuple[float, float]:
    x = math.sin(t * 0.42) * 5.8 + math.sin(t * 1.15) * 1.4
    y = math.cos(t * 0.36 + 0.6) * 4.6 + math.sin(t * 0.85) * 1.1
    return x, y


def attitude_worker() -> None:
    period = 1.0 / max(float(args.attitude_fps), 1.0)
    start = time.perf_counter()
    next_frame = start

    while attitude._live() is None and not attitude_stop_event.wait(0.01):
        pass

    while not attitude_stop_event.is_set():
        now = time.perf_counter()
        if now < next_frame:
            attitude_stop_event.wait(next_frame - now)
            continue

        pitch, roll, yaw = generated_attitude(now - start)
        state["pitch"] = pitch
        state["roll"] = roll
        state["yaw"] = yaw
        try:
            attitude.set_orientation(pitch=pitch, roll=roll, yaw=yaw)
        except RuntimeError:
            break

        next_frame += period
        if next_frame < now - period:
            next_frame = now + period


def translation_worker() -> None:
    period = 1.0 / max(float(args.translation_fps), 1.0)
    label_period = 1.0 / max(float(args.translation_label_fps), 0.25)
    start = time.perf_counter()
    next_frame = start
    next_label = start

    while translation_trace._live() is None and not translation_stop_event.wait(0.01):
        pass

    while not translation_stop_event.is_set():
        now = time.perf_counter()
        if now < next_frame:
            translation_stop_event.wait(next_frame - now)
            continue

        x, y = generated_translation(now - start)
        state["translation_x"] = x
        state["translation_y"] = y
        try:
            translation_trace.set_position(x, y)
            if now >= next_label:
                set_translation_labels(x, y)
                next_label = now + label_period
        except RuntimeError:
            break

        next_frame += period
        if next_frame < now - period:
            next_frame = now + period


def stream_worker() -> None:
    global stream_proc
    try:
        stream_proc = subprocess.Popen(stream_cmd, stdout=subprocess.PIPE)
    except FileNotFoundError:
        app.call_soon_threadsafe(lambda: set_status("v4l2-ctl was not found"))
        return
    except OSError as exc:
        app.call_soon_threadsafe(lambda exc=exc: set_status(f"stream start failed: {exc}"))
        return

    try:
        assert stream_proc.stdout is not None
        while not stop_event.is_set():
            frame_data = stream_proc.stdout.read(frame_bytes)
            if len(frame_data) != frame_bytes:
                state["last_error"] = "incomplete frame"
                app.call_soon_threadsafe(lambda: set_status("incomplete frame"))
                break

            raw = np.frombuffer(frame_data, dtype=np.uint16, count=frame_words)
            try:
                payload = make_phase_payload(raw)
            except Exception as exc:  # pragma: no cover - live hardware path
                state["last_error"] = str(exc)
                app.call_soon_threadsafe(lambda exc=exc: set_status(f"frame error: {exc}"))
                continue

            scatter.enqueue_prepared_points(payload, coalesce=True, include_metadata=False)
            state["frames"] += 1
            state["last_pack_ms"] = payload.pack_ms
            state["last_points"] = payload.point_count
            if state["frames"] == 1 or state["frames"] % 10 == 0:
                app.call_soon_threadsafe(update_metrics)
    finally:
        if stream_proc is not None:
            stream_proc.terminate()
            try:
                stream_proc.wait(timeout=1.0)
            except subprocess.TimeoutExpired:
                stream_proc.kill()
        stream_proc = None


def start_stream() -> None:
    global stream_thread
    if stream_thread is not None and stream_thread.is_alive():
        return
    stop_event.clear()
    stream_thread = threading.Thread(target=stream_worker, name="v4l2-phase-stream", daemon=True)
    stream_thread.start()
    status.set_value("stream starting")


def stop_stream() -> None:
    stop_event.set()
    if stream_proc is not None:
        stream_proc.terminate()
    status.set_value("stream stopping")


def print_metrics() -> None:
    snapshot = app.debug_snapshot()
    scatter_metrics = snapshot.get("gpu", {}).get("resources", {}).get("scatter", {})
    print(
        {
            "frames": state["frames"],
            "points": state["last_points"],
            "pack_ms": round(state["last_pack_ms"], 3),
            "scatter_updates": scatter_metrics.get("updates"),
            "upload_ms": scatter_metrics.get("last_upload_ms"),
            "queue_latency_ms": scatter_metrics.get("last_queue_latency_ms"),
        },
        flush=True,
    )


def make_fake_payload(kind: str) -> dg.ScatterPayload:
    if kind == "noise":
        x_values = debug_rng.uniform(-float(x_center), float(x_center), size=debug_points).astype(
            np.float32
        )
        y_values = debug_rng.uniform(-float(y_center), float(y_center), size=debug_points).astype(
            np.float32
        )
    else:
        x_values = debug_x_sample
        y_values = debug_y_sample
    x_norm = (x_values + x_center) / max(1.0, float(args.width - 1))
    y_norm = (y_center - y_values) / max(1.0, float(args.image_height - 1))
    if kind == "wave":
        phase = np.sin(x_norm * TAU * 4.0) + np.cos(y_norm * TAU * 3.0)
    elif kind == "rings":
        cx = x_norm - 0.5
        cy = y_norm - 0.5
        radius = np.sqrt(cx * cx + cy * cy)
        phase = np.sin(radius * TAU * 10.0)
    elif kind == "noise":
        phase = debug_rng.uniform(-np.pi, np.pi, size=debug_points)
    else:
        phase = np.linspace(-np.pi, np.pi, debug_points, dtype=np.float32)

    phase = np.asarray(phase, dtype=np.float32)
    phase = np.clip(phase, -np.pi, np.pi)
    frame = {
        "x": x_values,
        "y": y_values,
        "z": phase * np.float32(z_scale),
        "phase": phase,
    }
    return prepare_scatter_payload(frame, point_size=3.2)


def get_fake_payload(kind: str) -> dg.ScatterPayload:
    with debug_payloads_lock:
        payload = debug_payloads.get(kind)
    if payload is None:
        payload = make_fake_payload(kind)
        with debug_payloads_lock:
            debug_payloads[kind] = payload
    return payload


def apply_fake_payload(kind: str, payload: dg.ScatterPayload) -> None:
    scatter.set_prepared_points(payload, coalesce=True, update_metadata=False, fit=False)
    state["frames"] += 1
    state["last_pack_ms"] = payload.pack_ms
    state["last_points"] = payload.point_count
    status.set_value(
        f"debug {kind}: points={payload.point_count} pack={payload.pack_ms:.2f}ms"
    )


def inject_fake_points(kind: str) -> None:
    with debug_payloads_lock:
        cached = debug_payloads.get(kind)
    if cached is not None:
        apply_fake_payload(kind, cached)
        return

    status.set_value(f"building debug {kind}...")

    def worker() -> None:
        payload = get_fake_payload(kind)
        app.call_soon_threadsafe(lambda: apply_fake_payload(kind, payload))

    threading.Thread(target=worker, name=f"fake-scatter-{kind}", daemon=True).start()


def schedule_debug_reinject(kind: str, count: int, interval_ms: int) -> None:
    count = max(0, int(count))
    if count <= 0:
        return
    interval_s = max(1, int(interval_ms)) / 1000.0

    def worker() -> None:
        payload = get_fake_payload(kind)
        for _ in range(count):
            time.sleep(interval_s)
            app.call_soon_threadsafe(lambda payload=payload: apply_fake_payload(kind, payload))

    threading.Thread(target=worker, name=f"fake-reinject-{kind}", daemon=True).start()


with dg.HLayout(
    style={
        "width": "100%",
        "height": "100%",
        "min_height": 0,
        "align_items": "stretch",
        "overflow_y": "hidden",
    }
):
    with dg.Panel(
        "Camera",
        width=LEFT_PANEL_WIDTH,
        style={
            "height": "100%",
            "min_height": 0,
            "flex_shrink": 0,
            "overflow_y": "hidden",
            "padding": 5,
            "gap": 4,
            "font_size": 12,
            "line_height": "15px",
        },
    ):
        with dg.ScrollArea(
            axis="y",
            gap=5,
            style={
                "width": "100%",
                "min_height": 0,
                "flex_grow": 1,
                "flex_shrink": 1,
                "overflow_y": "auto",
            },
        ):
            status = dg.Label("ready", class_="compact-label", style=CONTROL_LABEL_STYLE)

            dg.Label("STREAM", class_="section-label", style=SECTION_LABEL_STYLE)
            with dg.FlowLayout(gap=4, row_gap=4):
                dg.Button(
                    "Start",
                    class_="tiny-control",
                    style=SMALL_BUTTON_STYLE,
                    on_click=start_stream,
                )
                dg.Button(
                    "Stop",
                    class_="tiny-control",
                    style=SMALL_BUTTON_STYLE,
                    on_click=stop_stream,
                )

            dg.Separator()
            dg.Label("VIEW", class_="section-label", style=SECTION_LABEL_STYLE)
            dg.Button(
                "Fit camera",
                class_="compact-control",
                style=CONTROL_BUTTON_STYLE,
                on_click=lambda: scatter.fit(),
            )
            with dg.FlowLayout(gap=4, row_gap=4):
                dg.Button(
                    "XY",
                    class_="tiny-control",
                    style=SMALL_BUTTON_STYLE,
                    on_click=lambda: scatter.view_xy(),
                )
                dg.Button(
                    "Iso",
                    class_="tiny-control",
                    style=SMALL_BUTTON_STYLE,
                    on_click=lambda: scatter.view_isometric(),
                )

            dg.Separator()
            dg.Label("FILTER", class_="section-label", style=SECTION_LABEL_STYLE)
            threshold_value = dg.Label(
                f"Threshold {float(args.threshold):0.2f}",
                class_="compact-label",
                style=CONTROL_LABEL_STYLE,
            )
            dg.Slider(
                float(args.threshold),
                min=0.0,
                max=3.0,
                step=0.05,
                on_change=set_threshold,
                style=CONTROL_SLIDER_STYLE,
            )

            dg.Separator()
            with dg.Collapsible("Debug points", expanded=False):
                dg.Label(
                    f"{debug_points:,} points",
                    class_="compact-label",
                    style=CONTROL_LABEL_STYLE,
                )
                with dg.FlowLayout(gap=4, row_gap=4):
                    dg.Button(
                        "Wave",
                        class_="tiny-control",
                        style=SMALL_BUTTON_STYLE,
                        on_click=lambda: inject_fake_points("wave"),
                    )
                    dg.Button(
                        "Rings",
                        class_="tiny-control",
                        style=SMALL_BUTTON_STYLE,
                        on_click=lambda: inject_fake_points("rings"),
                    )
                    dg.Button(
                        "Noise",
                        class_="tiny-control",
                        style=SMALL_BUTTON_STYLE,
                        on_click=lambda: inject_fake_points("noise"),
                    )
                    dg.Button(
                        "Ramp",
                        class_="tiny-control",
                        style=SMALL_BUTTON_STYLE,
                        on_click=lambda: inject_fake_points("ramp"),
                    )

    with dg.Panel(
        "Point cloud",
        style={
            "height": "100%",
            "min_height": 0,
            "flex_grow": 1,
            "flex_shrink": 1,
            "overflow_y": "hidden",
        },
    ):
        scatter = dg.Scatter3D(
            initial_frame,
            x="x",
            y="y",
            z="z",
            scalars="phase",
            colormap="turbo",
            point_size=3.2,
            axis_x="x",
            axis_y="y",
            axis_z="phase depth",
            grid=True,
            major_planes=True,
            minor_planes=True,
            grid_sticky=True,
            grid_all_edges=False,
            orientation_axes=True,
            scalar_bar=True,
            scalar_bar_title="phase",
            clim=(-float(np.pi), float(np.pi)),
            background=(0.02, 0.02, 0.03),
            lod=True,
            lod_threshold=50_000,
            interactive_render_scale=0.75,
            class_="main-scatter",
            key="main-scatter",
            style={
                "min_height": 0,
                "flex_grow": 1,
                "flex_shrink": 1,
                "align_self": "stretch",
            },
        )

    with dg.VLayout(
        style={
            "height": "100%",
            "min_height": 0,
            "width": RIGHT_PANEL_WIDTH,
            "flex_shrink": 0,
            "gap": 5,
            "overflow_y": "hidden",
        }
    ):
        with dg.Panel(
            "Attitude",
            style={
                "padding": 6,
                "gap": 4,
                "flex_shrink": 0,
                "height": ATTITUDE_PANEL_HEIGHT,
                "overflow_y": "hidden",
                "font_size": 12,
                "line_height": "15px",
            },
        ):
            attitude = dg.AttitudeSphere(
                size=args.attitude_size,
                show_grid=True,
                show_heading=True,
                show_readout=True,
                grid_quality="fast",
                class_="lidar-attitude",
                style={
                    "width": "100%",
                    "height": ATTITUDE_WIDGET_HEIGHT,
                    "flex_shrink": 0,
                },
            )

        with dg.Panel(
            "Translation",
            style={
                "padding": 5,
                "gap": 3,
                "flex_shrink": 0,
                "height": TRANSLATION_PANEL_HEIGHT,
                "overflow_y": "hidden",
                "font_size": 12,
                "line_height": "15px",
            },
        ):
            translation_trace = dg.TranslationTrace(
                size=args.translation_size,
                range_m=args.translation_range_m,
                ring_step_m=args.translation_ring_step_m,
                trail_points=args.translation_trail_points,
                class_="lidar-translation",
                style={
                    "width": "100%",
                    "height": args.translation_size,
                    "flex_shrink": 0,
                },
            )
            with dg.FlowLayout(gap=4, row_gap=2):
                translation_x_value = dg.Label(
                    "X 0.00 m",
                    class_="metric-label",
                    style=TRANSLATION_LABEL_STYLE,
                )
                translation_y_value = dg.Label(
                    "Y 0.00 m",
                    class_="metric-label",
                    style=TRANSLATION_LABEL_STYLE,
                )

        with dg.Panel(
            "Telemetry",
            style={
                "padding": 5,
                "gap": 2,
                "height": 90,
                "flex_grow": 0,
                "flex_shrink": 1,
                "min_height": 0,
                "overflow_y": "auto",
                "font_size": 12,
                "line_height": "15px",
            },
        ):
            points_value = dg.Label("Pts 0", class_="metric-label", style=RIGHT_LABEL_STYLE)
            pack_value = dg.Label("Pack 0.0 ms", class_="metric-label", style=RIGHT_LABEL_STYLE)
            frames_value = dg.Label("Frames 0", class_="metric-label", style=RIGHT_LABEL_STYLE)
            dg.Label(f"Step {sample_step}  Z {z_scale:g}", class_="metric-label", style=RIGHT_LABEL_STYLE)
            dg.Label(f"IMU {args.attitude_fps:g} Hz", class_="metric-label", style=RIGHT_LABEL_STYLE)

if args.autostart:
    threading.Timer(0.2, lambda: app.call_soon_threadsafe(start_stream)).start()
if args.debug_autoinject != "none":
    threading.Timer(
        0.2,
        lambda: app.call_soon_threadsafe(lambda: inject_fake_points(args.debug_autoinject)),
    ).start()
    if args.debug_reinject_count > 0:
        threading.Timer(
            0.45,
            lambda: schedule_debug_reinject(
                args.debug_autoinject,
                args.debug_reinject_count,
                args.debug_reinject_interval_ms,
            ),
        ).start()

if not args.no_attitude_stream:
    attitude_thread = threading.Thread(
        target=attitude_worker,
        name="lidar-attitude-stream",
        daemon=True,
    )
    attitude_thread.start()
if not args.no_translation_stream:
    translation_thread = threading.Thread(
        target=translation_worker,
        name="lidar-translation-stream",
        daemon=True,
    )
    translation_thread.start()

try:
    result = app.run(win)
    if args.benchmark_summary:
        snapshot = result.get("debug_snapshot", {})
        runtime = snapshot.get("runtime", {}) if isinstance(snapshot, dict) else {}
        gpu = snapshot.get("gpu", {}) if isinstance(snapshot, dict) else {}
        performance = runtime.get("performance", {}) if isinstance(runtime, dict) else {}
        gpu_perf = performance.get("gpu", {}) if isinstance(performance, dict) else {}
        primitive_stats = gpu_perf.get("primitive_stats", {}) if isinstance(gpu_perf, dict) else {}
        resources = gpu.get("resources", {}) if isinstance(gpu, dict) else {}
        scatter_snapshot = resources.get("scatter", {}) if isinstance(resources, dict) else {}
        print(
            {
                "window": (gpu.get("window") if isinstance(gpu, dict) else None),
                "present_mode": runtime.get("platform", {}).get("present_mode")
                if isinstance(runtime.get("platform"), dict)
                else None,
                "max_frame_latency": runtime.get("platform", {}).get("desired_maximum_frame_latency")
                if isinstance(runtime.get("platform"), dict)
                else None,
                "frames_rendered": runtime.get("frames_rendered"),
                "wall_fps": runtime.get("wall_fps"),
                "frame_ms": runtime.get("frame_ms"),
                "last_frame_ms": runtime.get("last_frame_ms"),
                "frame_work_ms": runtime.get("frame_work_ms"),
                "frame_base_pass_encode_ms": runtime.get("frame_base_pass_encode_ms"),
                "frame_scatter_pass_encode_ms": runtime.get("frame_scatter_pass_encode_ms"),
                "frame_overlay_pass_encode_ms": runtime.get("frame_overlay_pass_encode_ms"),
                "frame_encoder_finish_ms": runtime.get("frame_encoder_finish_ms"),
                "frame_submit_ms": runtime.get("frame_submit_ms"),
                "frame_present_ms": runtime.get("frame_present_ms"),
                "primitive_count": gpu_perf.get("last_primitive_instance_count")
                if isinstance(gpu_perf, dict)
                else None,
                "primitive_base_count": primitive_stats.get("base_count")
                if isinstance(primitive_stats, dict)
                else None,
                "primitive_base_area_px": primitive_stats.get("base_area_px")
                if isinstance(primitive_stats, dict)
                else None,
                "primitive_base_general_count": primitive_stats.get("base_general", {}).get("count")
                if isinstance(primitive_stats.get("base_general"), dict)
                else None,
                "primitive_base_general_area_px": primitive_stats.get("base_general", {}).get("area_px")
                if isinstance(primitive_stats.get("base_general"), dict)
                else None,
                "primitive_base_rounded_count": primitive_stats.get("base_rounded_solid", {}).get("count")
                if isinstance(primitive_stats.get("base_rounded_solid"), dict)
                else None,
                "primitive_base_rounded_area_px": primitive_stats.get("base_rounded_solid", {}).get("area_px")
                if isinstance(primitive_stats.get("base_rounded_solid"), dict)
                else None,
                "primitive_largest_base_rects": primitive_stats.get("largest_base_rects")
                if isinstance(primitive_stats, dict)
                else None,
                "text_count": gpu_perf.get("last_text_entry_count")
                if isinstance(gpu_perf, dict)
                else None,
                "scatter_effective_drawn": scatter_snapshot.get("effective_draw_point_count")
                if isinstance(scatter_snapshot, dict)
                else None,
                "scatter_upload_ms": scatter_snapshot.get("last_upload_ms")
                if isinstance(scatter_snapshot, dict)
                else None,
                "scatter_point_scale": scatter_snapshot.get("point_size_scale")
                if isinstance(scatter_snapshot, dict)
                else None,
                "scatter_static_render_scale": scatter_snapshot.get("static_render_scale")
                if isinstance(scatter_snapshot, dict)
                else None,
                "scatter_active_render_scale": scatter_snapshot.get("active_render_scale")
                if isinstance(scatter_snapshot, dict)
                else None,
                "last_points": state.get("last_points"),
                "last_pack_ms": state.get("last_pack_ms"),
                "attitude": {
                    "pitch": round(float(state.get("pitch", 0.0)), 2),
                    "roll": round(float(state.get("roll", 0.0)), 2),
                    "yaw": round(float(state.get("yaw", 0.0)), 2),
                },
                "translation": {
                    "x": round(float(state.get("translation_x", 0.0)), 2),
                    "y": round(float(state.get("translation_y", 0.0)), 2),
                },
            }
        )
    else:
        print(result)
finally:
    stop_event.set()
    attitude_stop_event.set()
    translation_stop_event.set()
    if stream_proc is not None:
        stream_proc.terminate()
