"""Python API for DragonGUI."""

from ._backend import BackendUnavailableError, backend_info, native_backend_available
from .app import App, LoadingScreen, run_with_loading
from .components import ComponentCtx, ComponentInstance, StateSlot, component
from .dialogs import (
    FileDialog,
    open_file_dialog,
    open_files_dialog,
    pick_folder_dialog,
    save_file_dialog,
)
from .diagnostics import register_thread_role, thread_role
from .manual import HelpSection, help
from .notifications import toast
from .runtime import ToastHandle
from .thread_monitor import ThreadMonitor
from .theme import Theme
from .terminal import Terminal
from .vdom import Patch, ResourceRef, VNode
from .widgets import (
    Badge,
    ArrowButton,
    BarChart,
    BarChartBar,
    BarChartData,
    BreadcrumbItem,
    BreadcrumbSelection,
    Breadcrumbs,
    Button,
    Checkbox,
    Collapsible,
    CodeEditor,
    ColorPicker,
    Command,
    CommandPalette,
    DataFrameTable,
    DateInput,
    DateTimeInput,
    DragDropPayload,
    DragNumber,
    DragSource,
    DragVector,
    DropTarget,
    DropZone,
    Dropdown,
    ExtensionWidget,
    FlowLayout,
    GridLayout,
    HLayout,
    Heatmap,
    HeatmapCell,
    Histogram,
    HistogramBins,
    HtmlReport,
    IconButton,
    Image,
    ImageButton,
    LED,
    Label,
    LinePlot,
    LogView,
    LoadingSpinner,
    ContextMenu,
    Menu,
    MenuBar,
    MenuItem,
    Modal,
    NavItem,
    NumberInput,
    Page,
    Pages,
    Pane,
    Panel,
    PieChart,
    ProgressBar,
    Property,
    PropertyChange,
    PropertyGrid,
    RadioButton,
    RadioGroup,
    RangeSlider,
    Scatter3D,
    ScatterPlot2D,
    ScatterFrameStream,
    ScatterHit,
    ScatterLiveFrame,
    LinePlotPayload,
    MeasureConstraints,
    PaintKeyEvent,
    PaintPointerEvent,
    ScatterPick,
    ScatterPayload,
    ScatterStreamMetrics,
    PaintContext,
    PaintWidget,
    ScrollArea,
    SearchBox,
    Selectable,
    SelectableList,
    Separator,
    Sidebar,
    Slider,
    SmallButton,
    Size,
    Spacer,
    Splitter,
    StatusBar,
    Tab,
    Tabs,
    TableSelection,
    TableSort,
    Tag,
    TextArea,
    TextInput,
    TimeInput,
    ToggleSwitch,
    Toolbar,
    ToolbarSeparator,
    TreeNode,
    TreeView,
    Tooltip,
    VLayout,
    Window,
    alert,
    confirm,
)


def link_cameras(*scatters: "Scatter3D") -> None:
    """Link two or more Scatter3D widgets so programmatic camera changes propagate between them."""
    for s in scatters:
        s.link_cameras(*(o for o in scatters if o is not s))


def unlink_cameras(*scatters: "Scatter3D") -> None:
    """Remove camera links between Scatter3D widgets."""
    for s in scatters:
        s.unlink_cameras(*(o for o in scatters if o is not s))


__all__ = [
    "App",
    "BackendUnavailableError",
    "ComponentCtx",
    "ComponentInstance",
    "FileDialog",
    "HelpSection",
    "Patch",
    "ResourceRef",
    "StateSlot",
    "Theme",
    "ToastHandle",
    "VNode",
    "Badge",
    "ArrowButton",
    "BarChart",
    "BarChartBar",
    "BarChartData",
    "BreadcrumbItem",
    "BreadcrumbSelection",
    "Breadcrumbs",
    "Button",
    "Checkbox",
    "Collapsible",
    "CodeEditor",
    "ColorPicker",
    "Command",
    "CommandPalette",
    "DataFrameTable",
    "DateInput",
    "DateTimeInput",
    "DragDropPayload",
    "DragNumber",
    "DragSource",
    "DragVector",
    "DropTarget",
    "DropZone",
    "Dropdown",
    "ExtensionWidget",
    "FlowLayout",
    "GridLayout",
    "HLayout",
    "Heatmap",
    "HeatmapCell",
    "Histogram",
    "HistogramBins",
    "HtmlReport",
    "IconButton",
    "Image",
    "ImageButton",
    "LED",
    "Label",
    "LinePlot",
    "LogView",
    "LoadingScreen",
    "LoadingSpinner",
    "ContextMenu",
    "Menu",
    "MenuBar",
    "MenuItem",
    "Modal",
    "NavItem",
    "NumberInput",
    "Page",
    "Pages",
    "Pane",
    "Panel",
    "PieChart",
    "ProgressBar",
    "Property",
    "PropertyChange",
    "PropertyGrid",
    "RadioButton",
    "RadioGroup",
    "RangeSlider",
    "Scatter3D",
    "ScatterPlot2D",
    "ScatterFrameStream",
    "ScatterHit",
    "ScatterLiveFrame",
    "LinePlotPayload",
    "MeasureConstraints",
    "PaintKeyEvent",
    "PaintPointerEvent",
    "ScatterPick",
    "ScatterPayload",
    "ScatterStreamMetrics",
    "PaintContext",
    "PaintWidget",
    "ScrollArea",
    "SearchBox",
    "Selectable",
    "SelectableList",
    "Separator",
    "Sidebar",
    "Slider",
    "SmallButton",
    "Size",
    "Spacer",
    "Splitter",
    "StatusBar",
    "Tab",
    "Tabs",
    "TableSelection",
    "TableSort",
    "Tag",
    "Terminal",
    "TextArea",
    "TextInput",
    "TimeInput",
    "ToggleSwitch",
    "Toolbar",
    "ToolbarSeparator",
    "TreeNode",
    "TreeView",
    "Tooltip",
    "VLayout",
    "Window",
    "alert",
    "backend_info",
    "component",
    "confirm",
    "open_file_dialog",
    "open_files_dialog",
    "pick_folder_dialog",
    "save_file_dialog",
    "native_backend_available",
    "toast",
    "help",
    "link_cameras",
    "unlink_cameras",
    "run_with_loading",
    "ThreadMonitor",
    "register_thread_role",
    "thread_role",
]

__version__ = "0.1.0"
