"""Python API for DragonGUI."""

from ._backend import BackendUnavailableError, backend_info, native_backend_available
from .app import App
from .components import ComponentCtx, ComponentInstance, StateSlot, component
from .dialogs import FileDialog
from .theme import Theme
from .vdom import Patch, ResourceRef, VNode
from .widgets import (
    Button,
    Checkbox,
    ColorPicker,
    DataFrameTable,
    Dropdown,
    HLayout,
    Image,
    Label,
    ContextMenu,
    Menu,
    MenuBar,
    MenuItem,
    Modal,
    NavItem,
    NumberInput,
    Page,
    Pages,
    Panel,
    ProgressBar,
    Scatter3D,
    Separator,
    Sidebar,
    Slider,
    Spacer,
    StatusBar,
    Tab,
    Tabs,
    TextInput,
    VLayout,
    Window,
    alert,
    confirm,
)

__all__ = [
    "App",
    "BackendUnavailableError",
    "ComponentCtx",
    "ComponentInstance",
    "FileDialog",
    "Patch",
    "ResourceRef",
    "StateSlot",
    "Theme",
    "VNode",
    "Button",
    "Checkbox",
    "ColorPicker",
    "DataFrameTable",
    "Dropdown",
    "HLayout",
    "Image",
    "Label",
    "ContextMenu",
    "Menu",
    "MenuBar",
    "MenuItem",
    "Modal",
    "NavItem",
    "NumberInput",
    "Page",
    "Pages",
    "Panel",
    "ProgressBar",
    "Scatter3D",
    "Separator",
    "Sidebar",
    "Slider",
    "Spacer",
    "StatusBar",
    "Tab",
    "Tabs",
    "TextInput",
    "VLayout",
    "Window",
    "alert",
    "backend_info",
    "component",
    "confirm",
    "native_backend_available",
]

__version__ = "0.1.0"
